### ISSUE TITLE
CTC example

### ISSUE THREAD

**Issue by Bhee** [daweileng/keras_MOD#2]
Please share an example code  for Bidirectional LSTM with CTC

**Comment by daweileng** [comment]
Please keep patience for a while. I'm reorganizing a demo project to show how to use all the features added in keras MOD

**Comment by daweileng** [comment]
Please check the new README and the newly added 'demo' folder

**Comment by Bhee** [comment]
Thank You.

**Comment by Bhee** [comment]
Thank you very much.

But when I trying to save model  using 
   model.save(file_path) shows error.

So I separately save the model in json string and weights. 
Is it right way?
For prediction, is it need to compile the model again?

Kindly give suggestions.

**Comment by daweileng** [comment]
I believe the right API should be model.save_weights(file_path).
For prediction, you'll need predict_on_batch() function.

**Comment by Bhee** [comment]
Thank you.  Saved the model
 predict_on_batch() works fine.

When I tried with bdlstm layer I got  following error 

_Using Theano backend.
model.floatX =  float32
model compiling...
('x = ', input_1)
('kernel = ', convolution2d_1_W)
('th_border_mode = ', 'valid')
('strides = ', (1, 1))
('image_shape = ', None)
('filter_shape = ', (1, 1, 3, 3))
('@Line277, input_shape = ', [None, 1, 26, None])
('@line278, output_shape = ', [None, None, 26])
    @Line526, masks = None
    @Line595, ndim =  2
    @Line606, sample_weight =  timedistributed_1_sample_weights
    @Line606, mask =  timedistributed_1_ctc_sm_mask
    @Line606, loss_function =  ctc_cost_for_train
CTC_for_train.cost is used
    @Line663, len of sample_weights =  1
    @Line664, type of sample_weights =  <class 'theano.tensor.var.TensorVariable'>
reshape_func compiled
Concatenating images
X_train2 shape: (60000, 168, 28)
y_train2 shape: (60000, 6)
model training
length of batch = 600
@Line1815,topology.py, there is upate@layer= timedistributed_1
Traceback (most recent call last):
  File "mnist_ctc_v9.py", line 227, in <module>
    sm_mask=traindata_mask, return_sm=True)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/engine/training.py", line 1316, in train_on_batch
    outputs = self.train_function[name](ins)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/backend/theano_backend.py", line 616, in __call__
    return self.function(*inputs)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 875, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 862, in __call__
    self.fn() if output_subset is None else\
ValueError: Input dimension mis-match. (input[0].shape[0] = 166, input[1].shape[0] = 10)
Apply node that caused the error: Elemwise{mul,no_inplace}(InplaceDimShuffle{1,2,0}.0, InplaceDimShuffle{1,x,0}.0)
Toposort index: 561
Inputs types: [TensorType(float32, 3D), TensorType(float32, (False, True, False))]
Inputs shapes: [(166, 11, 100), (10, 1, 100)]
Inputs strides: [(44, 4, 7304), (4, 4000, 40)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[AdvancedSubtensor(Elemwise{mul,no_inplace}.0, SliceConstant{None, None, None}, Elemwise{Cast{int32}}.0, ARange{dtype='int64'}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "mnist_ctc_v9.py", line 175, in <module>
    model = build_model_3(feadim=28, Nclass=10, loss=loss, optimizer=optimizer)
  File "mnist_ctc_v9.py", line 69, in build_model_3
    model.compile(loss=loss, optimizer=optimizer, sample_weight_mode='temporal')
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/engine/training.py", line 643, in compile
    output_loss = weighted_loss(y_true, y_pred, sample_weight, mask)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/objectives.py", line 129, in ctc_cost_for_train
    return CTC_for_train.cost(queryseq, scorematrix, queryseq_mask, scorematrix_mask)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/ctc_theano.py", line 366, in cost
    NLL, alphas = self.path_probability(queryseq_padded, scorematrix, queryseq_mask_padded, scorematrix_mask, blank_symbol)
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/ctc_theano.py", line 388, in path_probability
    pred_y = self._class_batch_to_labeling_batch(queryseq_padded, scorematrix, scorematrix_mask)  # (T, 2L+1, B), reshaped scorematrix
  File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/ctc_theano.py", line 315, in _class_batch_to_labeling_batch
    scorematrix = scorematrix * scorematrix_mask.dimshuffle(0, 'x', 1)                   # (T, C+1, B) * (T, 1, B)
_

Model is 
 ```
    net_input = Input(shape=(1, feadim, None))
    net_cnn   = Convolution2D(1, 3, 3, activation='relu', border_mode='valid')(net_input)   # input shape = (samples, channels, rows, cols)
    net_reshape = Permute((3,2))(net_cnn)
    forward_lstm  = LSTM(100, return_sequences=True, activation='tanh')(net_reshape)
    backward_lstm = LSTM(100, return_sequences=True, activation='tanh', go_backwards=True, keep_time_order=False)(net_reshape)
    net_output = Merge(mode='concat')([forward_lstm, backward_lstm])
    net_o2    = TimeDistributed(Dense(Nclass + 1,  activation='softmax'))(net_output)
    model     = Model(net_input, net_o2)    
    model.compile(loss=loss, optimizer=optimizer, sample_weight_mode='temporal')
    return model  
``` 
I am newbie to Keras. 
X_train2 shape: (60000, 168, 28)
but  in error shows
Inputs shapes: [(166, 11, 100), (10, 1, 100)]

 how 168 changed to 166?  anything wrong in the model creation?
I set batch size =100

Kindly help me.

**Comment by daweileng** [comment]
The shape changes because the border mode of `net_cnn` in your code is 'valid'. To keep the shape same with the input, use 'same' mode instead.
