### ISSUE TITLE
import  error

### ISSUE THREAD

**Issue by madhavsund** [daweileng/keras_MOD#3]
I downloaded PRECISE_CTC  from https://github.com/daweileng/Precise-CTC
while trying to execute the sample file mnist_ctc_v4.py 
I get the following import error

Using Theano backend.
Using gpu device 0: NVS 300 (CNMeM is disabled, cuDNN not available)
model.floatX =  float32
Traceback (most recent call last):
  File "mnist_ctc_v4.py", line 20, in <module>
    from NN_auxiliary import pad_sequence_
into_array
ImportError: No module named NN_auxiliary

help me to resolve.....

**Comment by daweileng** [comment]
The 'NN_auxiliary' is just a helper module written by me. The content has been changed a lot since the publication of Precise-CTC. The purpose of pad_sequence() function is just to simulate a word sequence with mnist single digits.

**Comment by madhavsund** [comment]
Ok.

modified **mnist_ctc_v4.py** code  given below. I just removed the 'Concatenating images' function _mnist_concatenate_image()_ in  of Precise_CTC

```
   (X_train, y_train), (X_test, y_test) = mnist.load_data()    
    y_train = np_utils.to_categorical(y_train, 10)
    print('X_train shape:', X_train.shape)                    # (B, T, D)
    print('y_train shape:', y_train.shape)                    # (B, L)  
    
    Nclass = 10
    B, T, D = X_train.shape   # D = 28
    L = y_train.shape[1]

    model = Sequential()
    model.add(LSTM(input_dim=D, output_dim=100,
                   return_sequences=True, activation='tanh'))   # output (B, T, C+1)   
    model.add(TimeDistributedDense(input_dim=100, output_dim=Nclass + 1, activation='softmax'))


    print("model compiling")     
    model.compile( optimizer='Adadelta', loss='ctc_cost_precise', metrics=['accuracy'])

    print("model training")
    batch=1
    for j in range(100):
        TE = 0.0
        TD = 0.0
        LOSS = 0.0
        n = 0
        TE2, TD2 = 0.0, 0.0
        batches = range(0, B, batch)
        shuffle = np.random.choice(batches, size=len(batches), replace=False)
        for i in shuffle:
	    X=X_train[i:i+batch,:,:].reshape([batch,T,D])

	    y=y_train[i:i+batch,:].reshape([batch, L])
            print X.shape, Y.shape
            ctcloss, cer, te, td, resultseq, resultseq_mask, scorematrixT = model.train_on_batch(X,y)
           
            TE += te
            TD += td
            LOSS += ctcloss*batch
            n += batch
            aveloss = LOSS / n
            print('epoch = %d, batch = %d, ave_loss = %0.4f, ave_CER = %0.4f, progress = %0.1f' % (j, i, aveloss, TE/TD, n/B))
```        

but , 
I get the following error :

> ('X_train shape:', (60000, 28, 28))
> ('y_train shape:', (60000, 10))
> model compiling
>     @Line526, masks = None
>     @Line595, ndim =  2
>     @Line606, sample_weight =  timedistributeddense_1_sample_weights
>     @Line606, mask =  timedistributeddense_1_ctc_sm_mask
>     @Line606, loss_function =  ctc_cost_precise
> queryseq Shape.0
> Traceback (most recent call last):
>   File "mnist_ctc.py", line 91, in <module>
>     model.compile( optimizer='Adadelta', loss='ctc_cost_precise', metrics=['accuracy'])
>   File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/models.py", line 362, in compile
>     **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/engine/training.py", line 643, in compile
>     output_loss = weighted_loss(y_true, y_pred, sample_weight, mask)
>   File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/objectives.py", line 105, in ctc_cost_precise
>     return CTC_precise.cost(queryseq, scorematrix, queryseq_mask, scorematrix_mask)
>   File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/ctc_theano.py", line 96, in cost
>     queryseq_padded, queryseq_mask_padded = self._pad_blanks(queryseq, blank_symbol, queryseq_mask)
>   File "/usr/local/lib/python2.7/dist-packages/Keras-1.0.6-py2.7.egg/keras/ctc_theano.py", line 298, in _pad_blanks
>     queryseq_mask_extended = queryseq_mask.dimshuffle(1, 0, 'x')                          # (L, B) -> (B, L, 1)
>   File "/usr/local/lib/python2.7/dist-packages/theano/tensor/var.py", line 362, in dimshuffle
>     pattern)
>   File "/usr/local/lib/python2.7/dist-packages/theano/tensor/elemwise.py", line 159, in __init__
>     (i, j, len(input_broadcastable)))
> ValueError: new_order[0] is 1, but the input only has 1 axes.



kindly help me to resolve

**Comment by daweileng** [comment]
Check the newly added 'demo' under https://github.com/daweileng/keras_MOD/tree/MOD_1.0.4/demo. There is a new demo script **mnist_ctc_v9.py** showing all the features added in Keras-MOD till now! There's also the required **NN_auxiliary.py** for you guys ;)

**Comment by rousseau-lium** [comment]
Hey! Thanks! Will check that right now! :)
